# Generated by Django 5.2.4 on 2025-07-22 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título principal do capítulo.', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL amigável do capítulo (gerado automaticamente).', max_length=200, unique=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição do capítulo.')),
                ('resumo', models.TextField(blank=True, help_text='Um breve resumo do capítulo.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Capítulo',
                'verbose_name_plural': 'Capítulos',
                'ordering': ['ordem', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Secao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da seção.', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL amigável da seção (gerado automaticamente).', max_length=200, unique=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição da seção dentro do capítulo.')),
                ('conteudo_html', models.TextField(blank=True, help_text='Conteúdo HTML da seção. Use tags HTML aqui.')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('capitulo', models.ForeignKey(help_text='Capítulo ao qual esta seção pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='secoes', to='conteudos_tcc.capitulo')),
            ],
            options={
                'verbose_name': 'Seção',
                'verbose_name_plural': 'Seções',
                'ordering': ['capitulo__ordem', 'ordem', 'titulo'],
                'unique_together': {('capitulo', 'slug')},
            },
        ),
    ]
