# Generated by Django 5.2.4 on 2025-07-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos_tcc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secao',
            name='imagem_ilustrativa',
            field=models.ImageField(blank=True, help_text='Imagem para ilustrar a seção.', null=True, upload_to='secao_imagens/'),
        ),
        migrations.AlterField(
            model_name='secao',
            name='conteudo_html',
            field=models.TextField(blank=True, help_text='Conteúdo HTML da seção.'),
        ),
    ]
