# Generated by Django 5.2.4 on 2025-07-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos_tcc', '0002_secao_imagem_ilustrativa_alter_secao_conteudo_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitulo',
            name='imagem_capa',
            field=models.ImageField(blank=True, help_text='Imagem de capa para o capítulo.', null=True, upload_to='capitulo_capas/'),
        ),
    ]
