# Generated by Django 5.2.4 on 2025-07-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos_tcc', '0003_capitulo_imagem_capa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secao',
            name='conteudo_html',
            field=models.TextField(blank=True, help_text='Conteúdo HTML da seção. Use tags HTML aqui.'),
        ),
    ]
