# Generated by Django 5.2.4 on 2025-07-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conteudos_tcc', '0004_alter_secao_conteudo_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Título do recurso (ex: 'Script de Instalação Nginx', 'Documentação Django').", max_length=200)),
                ('descricao', models.TextField(blank=True, help_text='Uma breve descrição do recurso.')),
                ('tipo', models.CharField(choices=[('DOWNLOAD', 'Download'), ('LINK', 'Link Externo')], default='LINK', help_text='Selecione o tipo de recurso: Download de arquivo ou Link externo.', max_length=10)),
                ('arquivo', models.FileField(blank=True, help_text="Para recursos do tipo 'Download', faça upload do arquivo aqui.", null=True, upload_to='recursos_downloads/')),
                ('url', models.URLField(blank=True, help_text="Para recursos do tipo 'Link Externo', insira a URL aqui.", null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('ordem', models.IntegerField(default=0, help_text='Ordem de exibição do recurso.')),
            ],
            options={
                'verbose_name': 'Recurso Adicional',
                'verbose_name_plural': 'Recursos Adicionais',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
